import { c as create_ssr_component, b as add_attribute, v as validate_component } from "../../../chunks/ssr.js";
const Eclipse = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { color = "hsla(213, 53%, 52%, 1)" } = $$props;
  if ($$props.color === void 0 && $$bindings.color && color !== void 0)
    $$bindings.color(color);
  return `<svg width="242" height="242" viewBox="0 0 242 242" fill="none" xmlns="http://www.w3.org/2000/svg" class="eclipse"><circle cx="121" cy="121" r="121"${add_attribute("fill", color, 0)}></circle></svg>`;
});
const css = {
  code: ".svelte-20gyls.svelte-20gyls{color:var(--color-white);text-decoration:none;--main-blue:hsla(215, 74%, 65%, 1);--secondary-blue:hsla(213, 53%, 52%, 1)}section.svelte-20gyls.svelte-20gyls:nth-of-type(1){display:flex;flex-direction:column;height:100vh;height:100dvh;width:100vw}.slide-2.svelte-20gyls.svelte-20gyls{background-color:hsla(195, 49%, 48%, 1)}.slide-3.svelte-20gyls.svelte-20gyls{background-color:hsla(174, 94%, 34%, 1)}.mouse.svelte-20gyls.svelte-20gyls{width:100%;height:25em;display:flex;justify-content:center;align-items:center;position:relative}picture.svelte-20gyls.svelte-20gyls{position:relative}.rat.svelte-20gyls.svelte-20gyls{position:absolute;top:0;left:0;right:0;bottom:0;display:flex;justify-content:center;align-items:center}img.svelte-20gyls.svelte-20gyls{max-width:100%;height:auto}h1.svelte-20gyls.svelte-20gyls,p.svelte-20gyls.svelte-20gyls{text-align:center}h1.svelte-20gyls.svelte-20gyls{font-size:1.25em;margin-bottom:1em}p.svelte-20gyls.svelte-20gyls{font-size:.8em;max-width:45ch;margin:auto;margin-top:0;margin-bottom:0}a.svelte-20gyls.svelte-20gyls:nth-of-type(1){margin-left:auto;color:var(--color-white);font-size:1.25em;padding:1em}button.svelte-20gyls.svelte-20gyls,a.svelte-20gyls.svelte-20gyls:nth-of-type(2){margin:auto;margin-bottom:2.5em;border-radius:.6em;width:80%;padding:1em;text-align:center;font-size:1em;border:none}.button-1.svelte-20gyls.svelte-20gyls{background-color:hsla(213, 53%, 52%, 1)}.button-2.svelte-20gyls.svelte-20gyls{background-color:hsla(198, 43%, 41%, 1)}.make-acc.svelte-20gyls.svelte-20gyls{background-color:hsla(173, 94%, 24%, 1)}.carousel.svelte-20gyls.svelte-20gyls{display:flex;scroll-snap-type:x mandatory;width:100%;overflow:auto;align-self:center}.carousel.svelte-20gyls>li.svelte-20gyls{scroll-behavior:smooth;scroll-snap-align:center;display:flex;flex-direction:column;height:100vh;height:100dvh;width:100vw;background-color:var(--main-blue)}.carousel-indicators.svelte-20gyls.svelte-20gyls{display:flex;justify-content:center;margin-bottom:1.8em;z-index:10}.indicator.svelte-20gyls.svelte-20gyls{width:.6em;height:.6em;border-radius:50%;border:1px solid lightgray;background-color:transparent;margin:0 5px;cursor:pointer}.indicator.active.svelte-20gyls.svelte-20gyls{background-color:var(--color-white)}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<main class="svelte-20gyls"><section class="svelte-20gyls"><ul class="carousel svelte-20gyls"><li class="svelte-20gyls"><section class="svelte-20gyls"><a href="/sign-up" class="svelte-20gyls" data-svelte-h="svelte-yhp0gb">Skip</a> <div class="mouse svelte-20gyls"> ${validate_component(Eclipse, "Eclipse").$$render($$result, {}, {}, {})} <picture class="rat svelte-20gyls" data-svelte-h="svelte-3phsyo"><source srcset="/characters/Rat.svg?format=avif" type="image/avif" class="svelte-20gyls"> <source srcset="/characters/Rat.svg?format=webp" class="svelte-20gyls">  <img src="/characters/Rat.svg" alt="rat image" height="250" class="svelte-20gyls"></picture></div> <div class="carousel-indicators svelte-20gyls" data-svelte-h="svelte-11gs5vf"><span class="indicator active svelte-20gyls" data-slide="0"></span> <span class="indicator svelte-20gyls" data-slide="1"></span> <span class="indicator svelte-20gyls" data-slide="2"></span></div> <h1 class="svelte-20gyls" data-svelte-h="svelte-k5bhe5">Learn languages</h1> <p class="svelte-20gyls" data-svelte-h="svelte-146b40h">Every household is different. Some only speak one language, others even as much as three!
                Learning more than one language has great neurological benefits for anyone at any age. With TuMi Mundo your child can learn up to 3 languages.</p> <button type="button" class="carousel-button right button-1 svelte-20gyls" data-target=".carousel" aria-label="right-button" data-svelte-h="svelte-r5g8mb">Continue</button></section></li> <li class="svelte-20gyls"><section class="slide-2 svelte-20gyls"><a href="/sign-up" class="svelte-20gyls" data-svelte-h="svelte-yhp0gb">Skip</a> <div class="mouse svelte-20gyls">${validate_component(Eclipse, "Eclipse").$$render($$result, { color: "hsla(199, 48%, 38%, 1)" }, {}, {})} <picture class="rat svelte-20gyls" data-svelte-h="svelte-3phsyo"><source srcset="/characters/Rat.svg?format=avif" type="image/avif" class="svelte-20gyls"> <source srcset="/characters/Rat.svg?format=webp" class="svelte-20gyls">  <img src="/characters/Rat.svg" alt="rat image" height="250" class="svelte-20gyls"></picture></div> <div class="carousel-indicators svelte-20gyls" data-svelte-h="svelte-11rnsur"><span class="indicator svelte-20gyls" data-slide="0"></span> <span class="indicator active svelte-20gyls" data-slide="1"></span> <span class="indicator svelte-20gyls" data-slide="2"></span></div> <h1 class="svelte-20gyls" data-svelte-h="svelte-19hv738">Test the progress</h1> <p class="svelte-20gyls" data-svelte-h="svelte-1muztiy">During the learning journal you can measure the improvement of your child.  
                There is an option to share the data with researchers to further improve the method and participate in special researches! You can manage the option to share your data at any given time in the app.</p> <button type="button" class="carousel-button right button-2 svelte-20gyls" data-target=".carousel" aria-label="right-button" data-svelte-h="svelte-16u5t3c">Continue</button></section></li> <li class="svelte-20gyls"><section class="slide-3 svelte-20gyls"><a href="/sign-up" class="svelte-20gyls" data-svelte-h="svelte-yhp0gb">Skip</a> <div class="mouse svelte-20gyls">${validate_component(Eclipse, "Eclipse").$$render($$result, { color: "hsla(173, 95%, 25%, 1)" }, {}, {})} <picture class="rat svelte-20gyls" data-svelte-h="svelte-3phsyo"><source srcset="/characters/Rat.svg?format=avif" type="image/avif" class="svelte-20gyls"> <source srcset="/characters/Rat.svg?format=webp" class="svelte-20gyls">  <img src="/characters/Rat.svg" alt="rat image" height="250" class="svelte-20gyls"></picture></div> <div class="carousel-indicators svelte-20gyls" data-svelte-h="svelte-1hbnct5"><span class="indicator svelte-20gyls" data-slide="0"></span> <span class="indicator svelte-20gyls" data-slide="1"></span> <span class="indicator active svelte-20gyls" data-slide="2"></span></div> <h1 class="svelte-20gyls" data-svelte-h="svelte-ghyido">See the results</h1> <p class="svelte-20gyls" data-svelte-h="svelte-z7ymj7">See the results of the tests and watch as your child learns a language with TuMi Mundo.
              The older your child becomes the further into the method you go, it starts with listening, it ends with being able to have a full conversation.</p> <a href="/sign-up" class="make-acc svelte-20gyls" data-svelte-h="svelte-1ru0itz">Make an account</a></section></li></ul></section> </main>`;
});
export {
  Page as default
};
